export { default as Landing } from './Landing/Landing'
export { default as Login } from './Login/Login'
export { default as Signup } from './Signup/Signup'
export { default as Contact } from './Contact/Contact'
export { default as TeacherLogin} from './TeacherLogin/TeacherLogin'
export { default as TeacherSignup} from './TeacherSignup/TeacherSignup'
export { default as StudentProfile} from './StudentProfile/StudentProfile'
export { default as Pendingassn } from './Pendingassn/Pendingassn'
export { default as Submitassn } from './Submitassn/Submitassn'
export { default as Subcomplete } from './Subcomplete/Subcomplete'
export { default as TeacherProfile} from './TeacherProfile/TeacherProfile'
export { default as About} from './About/About'

