export { default as Navbar } from './Navbar/Navbar'
export { default as Pendingassn_comp } from './Pendingassn_comp/Pendingassn_comp'
export { default as Aboout } from './Aboout/Aboout'
export {default as Tutorial} from './Tutorial/Tutorial'
export {default as TeTutorial} from './Tutorial/TeTutorial'

export { default as Home } from './Landing/Home/Home'
export { default as Contacts } from './Contacts/Contacts'
export { default as Submitassn_comp } from './Submitassn_comp/Submitassn_comp'
export { default as Subcomplete_comp } from './Subcomplete_comp/Subcomplete_comp'
